### Simple Get
GET http://localhost:8080/Color
###
GET http://localhost:8080/Category
###
GET http://localhost:8080/Article
###
GET http://localhost:8080/Product
###
GET http://localhost:8080/Material

### Get by Id
GET http://localhost:8080/Color/1
###
GET http://localhost:8080/Category/1
###
GET http://localhost:8080/Article/1
###
GET http://localhost:8080/Product/1
###
GET http://localhost:8080/Material/1
###
POST http://localhost:9000/Category/add
Content-Type: application/json

{
  "name" : "test4",
  "acronym": "test4",
  "type": "Material"
}
###
POST http://localhost:9000/Category/add
Content-Type: application/json

{
  "name" : "test3",
  "acronym": "test3",
  "type": "Product"
}
###
POST http://localhost:9000/Size/add
Content-Type: application/json

  {
    "size": 65
  }
###
POST http://localhost:9000/Color/add
Content-Type: application/json

{
  "name": "55A",
  "colorCode": "TEST"
}
###
POST http://localhost:9000/Material/add
Content-Type: application/json

{
  "name": "Folie",
  "value": 1,
  "minValue": 0
}
###
POST http://localhost:9000/Product/add
Content-Type: application/json

{
  "name": "TEST 49 34",
  "value": 100,
  "minValue": 1000
}
###
PUT http://localhost:9000/Article/update
Content-Type: application/json

{
"name": "BA 49 34",
"value": 100,
"minValue": 1000
}
###
PUT http://localhost:9000/Category/update
Content-Type: application/json

{
  "name": "TESTWERT",
  "acronym": "TEST"
}

###
DELETE http://localhost:9000/Size/delete/3
###
DELETE http://localhost:9000/Color/delete/1