### Simple Get
GET http://localhost:8080/Color
###
GET http://localhost:8080/Category
###
GET http://localhost:8080/Article
###
GET http://localhost:8080/Product
###
GET http://localhost:8080/Material

### Get by Id
GET http://localhost:8080/Color/1
###
GET http://localhost:8080/Category/1
###
GET http://localhost:8080/Article/1
###
GET http://localhost:8080/Product/1
###
GET http://localhost:8080/Material/1
###
POST http://localhost:9000/Size/add
Content-Type: application/json

  {
    "size": 65
  }
###
POST http://localhost:9000/Color/add
Content-Type: application/json

{
  "name": "55A",
  "colorCode": "TEST"
}

###
DELETE http://localhost:9000/Size/delete/3
###
DELETE http://localhost:9000/Color/delete/1