GET http://localhost:8080/regal/Regal-1

###
GET http://localhost:8080/regal
###
DELETE http://localhost:8080/lieferant/delete/1
###
DELETE http://localhost:8080/regal/delete/1
###
GET http://localhost:8080/lieferant

###
POST http://localhost:8080/regal/addregal
Content-Type: application/json

  {
    "name": "Regal-52344",
    "max_anzahl_faecher": 10,
    "fach_ids": [
      1,
      2,
      3
    ]
  }