GET http://localhost:8080/regal/Regal-1

###
GET http://localhost:8080/regal
###
GET http://localhost:8080/shelf
###
GET http://localhost:8080/supplier
###
GET http://localhost:8080/type
###
GET http://localhost:8080/ware
###
GET http://localhost:8080/ware/product
###
GET http://localhost:8080/ware/material
###
DELETE http://localhost:8080/lieferant/delete/1
###
DELETE http://localhost:8080/regal/delete/1
###
GET http://localhost:8080/supplier
###
GET http://localhost:8080/regal/queries/regal-fach
###
GET http://localhost:8080/fach/queries/regal-fach-ware
###
POST http://localhost:8080/regal/add
Content-Type: application/json

  {
    "name": "Regal-52344",
    "maxAmountShelfs" : 10,
    "fach_ids": [
      1,
      2,
      3
    ]
  }

###
POST http://localhost:8080/supplier/add
Content-Type: application/json

  {
    "name": "lolsasfsddsddsf",
    "link": "asssgsdsd",
    "deliveryTime" : 2
  }

###
DELETE http://localhost:8080/supplier/delete/3

###
GET http://localhost:8080/type
