var searchData=
[
  ['id_0',['Id',['../class_frontend_1_1_asp_mvc_1_1_models_1_1_identity_model.html#a885750c086cea072505b2b0adbbcb105',1,'Frontend.AspMvc.Models.IdentityModel.Id()'],['../class_frontend_1_1_logic_1_1_entities_1_1_identity_entity.html#a23ff8ba7e93dff23268147548629d066',1,'Frontend.Logic.Entities.IdentityEntity.Id()'],['../class_frontend_1_1_logic_1_1_models_1_1_identity_model.html#a28256d43664f401d434c89309da4f90f',1,'Frontend.Logic.Models.IdentityModel.Id()']]],
  ['idataaccess_1',['IDataAccess',['../interface_frontend_1_1_logic_1_1_contracts_1_1_i_data_access.html',1,'Frontend::Logic::Contracts']]],
  ['idataaccess_3c_20tentity_20_3e_2',['IDataAccess&lt; TEntity &gt;',['../interface_frontend_1_1_logic_1_1_contracts_1_1_i_data_access.html',1,'Frontend::Logic::Contracts']]],
  ['idataaccess_3c_20tmodel_20_3e_3',['IDataAccess&lt; TModel &gt;',['../interface_frontend_1_1_logic_1_1_contracts_1_1_i_data_access.html',1,'Frontend::Logic::Contracts']]],
  ['identityentity_4',['IdentityEntity',['../class_frontend_1_1_logic_1_1_entities_1_1_identity_entity.html',1,'Frontend::Logic::Entities']]],
  ['identitymodel_5',['IdentityModel',['../class_frontend_1_1_asp_mvc_1_1_models_1_1_identity_model.html',1,'Frontend.AspMvc.Models.IdentityModel'],['../class_frontend_1_1_logic_1_1_models_1_1_identity_model.html',1,'Frontend.Logic.Models.IdentityModel']]],
  ['iidentifyable_6',['IIdentifyable',['../interface_frontend_1_1_logic_1_1_contracts_1_1_i_identifyable.html',1,'Frontend::Logic::Contracts']]],
  ['image_2dsize_7',['image-size',['../md__frontend__multiflex__frontend__multi_flex__frontend__web_app_obj__host_node_modules_image_size__readme.html',1,'']]],
  ['indexof_8',['indexOf',['../md__frontend__multiflex__frontend__multi_flex__frontend__web_app_obj__host_node_modules_indexof__readme.html',1,'']]],
  ['inflight_9',['inflight',['../md__frontend__multiflex__frontend__multi_flex__frontend__web_app_obj__host_node_modules_inflight__r_e_a_d_m_e.html',1,'']]],
  ['inherit_10',['inherit',['../md__frontend__multiflex__frontend__multi_flex__frontend__web_app_obj__host_node_modules_component_inherit__readme.html',1,'']]],
  ['insertasync_11',['InsertAsync',['../interface_frontend_1_1_logic_1_1_contracts_1_1_i_data_access.html#a01b7970a85291ff679576c2241115439',1,'Frontend.Logic.Contracts.IDataAccess.InsertAsync(T element)'],['../interface_frontend_1_1_logic_1_1_contracts_1_1_i_data_access.html#aed548204434684b9318f07aac4440a59',1,'Frontend.Logic.Contracts.IDataAccess.InsertAsync(IEnumerable&lt; T &gt; elements)'],['../class_frontend_1_1_logic_1_1_controllers_1_1_generic_controller.html#a7e9f894dc0298bd954e9e00d9d8d9829',1,'Frontend.Logic.Controllers.GenericController.InsertAsync(TEntity entity)'],['../class_frontend_1_1_logic_1_1_controllers_1_1_generic_controller.html#a29b8c570fcaf0ec345ffd943f103d66b',1,'Frontend.Logic.Controllers.GenericController.InsertAsync(IEnumerable&lt; TEntity &gt; entities)']]],
  ['install_12',['Install',['../md__frontend__multiflex__frontend__multi_flex__frontend__web_app_obj__host_node_modules_detect_node__readme.html',1,'']]],
  ['installation_13',['Installation',['../md__frontend__multiflex__frontend__multi_flex__frontend__web_app_obj__host_node_modules__types_node__r_e_a_d_m_e.html',1,'(Global Namespace)'],['../md__frontend__multiflex__frontend__multi_flex__frontend__web_app_obj__host_node_modules__types_semver__r_e_a_d_m_e.html',1,'(Global Namespace)'],['../md__frontend__multiflex__frontend__multi_flex__frontend__web_app_obj__host_node_modules_electronf3c0b48e86324347e8f7505002ec465d.html',1,'(Global Namespace)']]],
  ['is_20_3ca_20href_3d_22https_3a_2f_2ftravis_2dci_2eorg_2fsindresorhus_2fis_22_20_3e_3cimg_20src_3d_22https_3a_2f_2ftravis_2dci_2eorg_2fsindresorhus_2fis_2esvg_3fbranch_3dmaster_22_20alt_3d_22build_20status_22_2f_3e_3c_2fa_3e_14',['is &lt;a href=&quot;https://travis-ci.org/sindresorhus/is&quot; &gt;&lt;img src=&quot;https://travis-ci.org/sindresorhus/is.svg?branch=master&quot; alt=&quot;Build Status&quot;/&gt;&lt;/a&gt;',['../md__frontend__multiflex__frontend__multi_flex__frontend__web_app_obj__host_node_modules__sindresorhus_is_readme.html',1,'']]],
  ['is_2dcore_2dmodule_20_3csup_3e_3ca_20href_3d_22https_3a_2f_2fnpmjs_2eorg_2fpackage_2fis_2dcore_2dmodule_22_20_3e_3cimg_20src_3d_22https_3a_2f_2fversionbadg_2ees_2finspect_2djs_2fis_2dcore_2dmodule_2esvg_22_20alt_3d_22version_20badge_22_2f_3e_3c_2fa_3e_3c_2fsup_3e_15',['is-core-module &lt;sup&gt;&lt;a href=&quot;https://npmjs.org/package/is-core-module&quot; &gt;&lt;img src=&quot;https://versionbadg.es/inspect-js/is-core-module.svg&quot; alt=&quot;Version Badge&quot;/&gt;&lt;/a&gt;&lt;/sup&gt;',['../md__frontend__multiflex__frontend__multi_flex__frontend__web_app_obj__host_node_modules_is_core_module__r_e_a_d_m_e.html',1,'']]],
  ['is_2dnumber_2dlike_16',['is-number-like',['../md__frontend__multiflex__frontend__multi_flex__frontend__web_app_obj__host_node_modules_is_number_like__r_e_a_d_m_e.html',1,'']]],
  ['isarray_17',['isarray',['../md__frontend__multiflex__frontend__multi_flex__frontend__web_app_obj__host_node_modules_has_binaaca1c12235ea3f8da597aeed8f8f35cd.html',1,'(Global Namespace)'],['../md__frontend__multiflex__frontend__multi_flex__frontend__web_app_obj__host_node_modules_isarray__r_e_a_d_m_e.html',1,'(Global Namespace)'],['../md__frontend__multiflex__frontend__multi_flex__frontend__web_app_obj__host_node_modules_socket_i7dee7a21c66ba66ea2bd2dd4272f5ab4.html',1,'(Global Namespace)'],['../md__frontend__multiflex__frontend__multi_flex__frontend__web_app_obj__host_node_modules_socket_i2ba51cbdd77f5c22e6255baf7f6db275.html',1,'(Global Namespace)']]],
  ['isessionwrapper_18',['ISessionWrapper',['../interface_frontend_1_1_asp_mvc_1_1_modules_1_1_session_1_1_i_session_wrapper.html',1,'Frontend::AspMvc::Modules::Session']]],
  ['iversionable_19',['IVersionable',['../interface_frontend_1_1_logic_1_1_contracts_1_1_i_versionable.html',1,'Frontend::Logic::Contracts']]]
];
