var searchData=
[
  ['account_0',['Account',['../namespace_frontend_1_1_asp_mvc_1_1_models_1_1_account.html',1,'Frontend.AspMvc.Models.Account'],['../namespace_frontend_1_1_logic_1_1_models_1_1_account.html',1,'Frontend.Logic.Models.Account']]],
  ['aspmvc_1',['AspMvc',['../namespace_frontend_1_1_asp_mvc.html',1,'Frontend']]],
  ['common_2',['Common',['../namespace_frontend_1_1_logic_1_1_modules_1_1_common.html',1,'Frontend::Logic::Modules']]],
  ['configuration_3',['Configuration',['../namespace_frontend_1_1_logic_1_1_modules_1_1_configuration.html',1,'Frontend::Logic::Modules']]],
  ['contracts_4',['Contracts',['../namespace_frontend_1_1_logic_1_1_contracts.html',1,'Frontend::Logic']]],
  ['controllers_5',['Controllers',['../namespace_frontend_1_1_asp_mvc_1_1_controllers.html',1,'Frontend.AspMvc.Controllers'],['../namespace_frontend_1_1_logic_1_1_controllers.html',1,'Frontend.Logic.Controllers']]],
  ['datacontext_6',['DataContext',['../namespace_frontend_1_1_logic_1_1_data_context.html',1,'Frontend::Logic']]],
  ['entities_7',['Entities',['../namespace_frontend_1_1_logic_1_1_entities.html',1,'Frontend::Logic']]],
  ['exceptions_8',['Exceptions',['../namespace_frontend_1_1_logic_1_1_modules_1_1_exceptions.html',1,'Frontend::Logic::Modules']]],
  ['extensions_9',['Extensions',['../namespace_frontend_1_1_asp_mvc_1_1_extensions.html',1,'Frontend::AspMvc']]],
  ['facades_10',['Facades',['../namespace_frontend_1_1_logic_1_1_facades.html',1,'Frontend::Logic']]],
  ['frontend_11',['Frontend',['../namespace_frontend.html',1,'']]],
  ['logic_12',['Logic',['../namespace_frontend_1_1_logic.html',1,'Frontend']]],
  ['models_13',['Models',['../namespace_frontend_1_1_asp_mvc_1_1_models.html',1,'Frontend.AspMvc.Models'],['../namespace_frontend_1_1_logic_1_1_models.html',1,'Frontend.Logic.Models']]],
  ['modules_14',['Modules',['../namespace_frontend_1_1_asp_mvc_1_1_modules.html',1,'Frontend.AspMvc.Modules'],['../namespace_frontend_1_1_logic_1_1_modules.html',1,'Frontend.Logic.Modules']]],
  ['orders_15',['Orders',['../namespace_frontend_1_1_logic_1_1_entities_1_1_orders.html',1,'Frontend::Logic::Entities']]],
  ['restapi_16',['RestApi',['../namespace_frontend_1_1_logic_1_1_modules_1_1_rest_api.html',1,'Frontend::Logic::Modules']]],
  ['session_17',['Session',['../namespace_frontend_1_1_asp_mvc_1_1_modules_1_1_session.html',1,'Frontend::AspMvc::Modules']]],
  ['unittest_18',['UnitTest',['../namespace_frontend_1_1_logic_1_1_unit_test.html',1,'Frontend::Logic']]],
  ['view_19',['View',['../namespace_frontend_1_1_asp_mvc_1_1_models_1_1_view.html',1,'Frontend::AspMvc::Models']]]
];
