name: Docker Image CI Backend
 
on:
  push:
    paths: 'MultiFlex/API/**'
  workflow_dispatch:

env:
  DOCKER_CONTAINER: multiflex-backend
  REGISTRY: ghcr.io
  IMAGE_NAME: multiflex-backend

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to the Container registry (Github container registry)
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build API docker image
      run: |
        cd MultiFlex/API/RestApi
        docker build . --tag ${{ env.IMAGE_NAME }}
    
    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
        
  start-docker-container-on-vm:
    needs:
      - build-and-push-docker-image
    runs-on: ubuntu-20.04
    steps:
      - name: Install ssh key Test
        uses: caberger/install-ssh-key@v1.0
        with:
            ssh-private-key:  ${{ secrets.SSH_PRIVATE_KEY }}
            user: ${{ secrets.REMOTE_USER }}
            server: ${{ secrets.REMOTE_HOST }}
            alias: server

      - name: test connection
        run: |
          echo "this is a test" > ~/test.txt
          scp ~/test.txt server:~/
          ssh server "ls -l ~"
          
      - name: Install ssh key
        uses: caberger/install-ssh-key@v1.0
        with:
            ssh-private-key:  ${{ secrets.SSH_PRIVATE_KEY }}
            user: ${{ secrets.REMOTE_USER }}
            server: ${{ secrets.REMOTE_HOST }}
            alias: server

      - name: Remove existing container
        run: |
          ssh server "sudo docker stop ${{ env.DOCKER_CONTAINER }} || echo 'Container doesnt exist!'"
          ssh server "sudo docker rm ${{ env.DOCKER_CONTAINER }} || echo 'No container to remove'"
          
      - name: Pull latest docker image and run container
        run: | 
          IMAGE_PULL_URL=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          IMAGE_PULL_URL=$(echo $IMAGE_PULL_URL | tr '[A-Z]' '[a-z]')
          ssh server "sudo docker pull $IMAGE_PULL_URL"
          ssh server "sudo docker run -d --name ${{ env.DOCKER_CONTAINER }} -p 8080:80 -p 8081:443 $IMAGE_PULL_URL"
