name: MultiFlex

on:
  push:
    branches:
      - main

jobs:
  buildAndDeployDoxygen:
    name: Build and Deploy Doxygen ✨
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: "true"

    - name: Install Doxygen
      run: sudo apt-get install doxygen graphviz -y
      shell: bash

    - name: Generate Doxygen Documentation
      run: doxygen .github/workflows/DoxyFile
      shell: bash

    - name: Deploy 📱
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: publish
        folder: docs/html